### ISSUE TITLE
Software crashes on 5V boards

### ISSUE THREAD

**Issue by daan03er** [sparkfun/SparkFun_ADS1219_Arduino_Library#5]
When running the every example code, the software crashes after around 10 seconds. The reset and power on and off does not reinstate de measurements, only reuploading the code makes sure that the software starts running again. However, crashes again after 10 seconds. 

I have the internal I2C pullup resistors disabled and replaced with external 5K ohm resistors. The GND, 5V and address pins are all connected correctly. I am not using the data ready pin. 

The IN1 is connected to ground and IN0 is connected to my analog signal.

**Comment by PaulZC** [comment]
Hi @daan03er ,

I don't have a Leonardo, so I can't fully replicate what you are seeing. I will try running it on a 5V ATmega328P board, just to see if it demonstrates the same issue.

I suspect this is something to do with either the Leonardo, or your set-up. But, from your description, you seem to be doing what I would do.

- Does the example crash if you disconnect the analog signal?
- Does it crash if you disconnect IN1 from ground - and use ```myADC.setInputMultiplexer(ADS1219_CONFIG_MUX_SINGLE_0);``` ?
- Is your signal going higher than 5V?
- Or lower than 0V?

Best,
Paul

**Comment by daan03er** [comment]
Hi Paul, 

Yes, the crash still occurs when the analog signal is disconnected. It is however after a longer periode of time compared to when the analog signal is connected. 


When i set myADC.setInputMultiplexer(ADS1219_CONFIG_MUX_SINGLE_0) it does not crash when the analog signal is disconnected, when it is connected it does crash. 

No, the signal is set on 1.5V

**Comment by daan03er** [comment]
Nevermind, it just crashed

**Comment by PaulZC** [comment]
I've got the example running on a 5V ATmega328P. No crashing. Everything is working.

Please share a photo of your board, and the wires linking them.

I wonder if this is something to do with I2C clock stretching? I know the Due does not support clock stretching. Maybe the Leonardo has the same issue?

Thank you,.
Paul

**Comment by PaulZC** [comment]
Oh. Hang on... My board just crashed...!

Investigating...

**Comment by PaulZC** [comment]
OK. I _think_ this has something to do with the reference voltage. I just tried the following and it seems to have fixed the issue:

* Connect REFP to VDDA - the pins are adjacent on the SparkX PCB
* Connect REFN to GND - ditto
* Open Example6
* Change [this line](https://github.com/sparkfun/SparkFun_ADS1219_Arduino_Library/blob/0af3758b9f45e147a8705cc053975499fef8111e/examples/Example06_ReferenceVoltage/Example06_ReferenceVoltage.ino#L88) to:

```float milliVolts = myADC.getConversionMillivolts(5000.0); // Convert to millivolts - using a reference of 5000mV```

Let me know if this fixes the issue on Leonardo too.

Thanks,
Paul

**Comment by daan03er** [comment]
This does seems to be working, the program has been running for a minute now, gonna keep it running longer. 

Do you have any idea what the issue is/was exactly?

**Comment by PaulZC** [comment]
Not exactly... The internal reference is 2.048V. Maybe the chip doesn't like common mode voltages well outside that? Just a guess... But it does seem to have fixed it.

I'm going to close this as I think we have resolved the issue - and that it's nothing to do with the library. But I will pin it, to make it easier to find.

Please reopen if you see more weirdness...

All the best,
Paul

**Comment by daan03er** [comment]
I think it just crashed after 8 minutes.... 

Running again now

**Comment by PaulZC** [comment]
OK. Mine's still running... I'm not sure what else to suggest...?

Maybe double-check those pull-ups? Are you able to put a 'scope or logic analyzer on the SDA and SCL lines?

Or, are you able to test it on a 3.3V board - just to confirm that voltage is the critical issue?

**Comment by daan03er** [comment]
I'll put a scope and the SDA and SCL pins. 

I dont have a 3v3 board.

**Comment by daan03er** [comment]
Hi Paul, 

After furter investigation, the crash occurs in the following part: 
![afbeelding](https://github.com/sparkfun/SparkFun_ADS1219_Arduino_Library/assets/82929425/3287a918-eb71-457f-9153-00092a6c3382)
I do get the serial message: "dataready reg thing".
However, after this it crashes. It happens after 10-15 minutes so I am very puzzeled.

**Comment by PaulZC** [comment]
Hi @daan03er ,

That line of code is just a standard Wire register read. The actual read is done by [the Toolkit](https://github.com/sparkfun/SparkFun_Toolkit/blob/ef8752bffcb25b15bb6d87799a3b06c29f2f02c0/src/sfeTkArdI2C.cpp#L175-L178).

I really don't understand why the read is crashing...

Are you powering the ADS1219 directly from 5V? And pulling up SCL and SDA to 5V also?

Please post a photo of your boards and the connections between them. It always helps...

Best wishes,
Paul

**Comment by daan03er** [comment]
![WhatsApp Image 2024-03-14 at 11 44 28](https://github.com/sparkfun/SparkFun_ADS1219_Arduino_Library/assets/82929425/00761c2e-f008-43a1-95cf-752f48606969)

The ADS1219 is supplied with 5V and the I2C pullups are also to 5V.

**Comment by PaulZC** [comment]
Another little trick is to put ```Serial.flush();``` after each debug print. That way the code will wait until the serial data has actually been sent before it moves on. Then you can be absolutely sure where the crash is happening. The crash _may_ be happening a little later, before the message is actually printed.

Thanks for the photo. Taking a look now.

**Comment by daan03er** [comment]
Could it be that at 3v3 the I2C pullup resistors work better then at 5V? Right now I have 5Kohm pullup resistors.

**Comment by PaulZC** [comment]
Your circuit looks OK. I can't see anything wrong...  Except I can't make out your resistor values. 5K should be Green Black Red. Or Green Black Black Brown. They look like 500 Ohm: Green Black Black Black?

**Comment by daan03er** [comment]
I measured them to be sure and they are 5K.

**Comment by PaulZC** [comment]
That's good. I'm pleased it is working.

Some decoupling capacitors may help. I suggest adding 2.2uF and 0.1uF close to the AVDD and DVDD pins.
